// <auto-generated />
namespace AluPlast.ControlLoader.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDescriptionToPhoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDescriptionToPhoto));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101028029_AddDescriptionToPhoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
